"""Evaluate the pre-registered success criteria of docs/OVERNIGHT_PLAN.md against whatever the overnight queue has produced, and write docs/OVERNIGHT_RESULTS.md.
Missing inputs are reported as "not run", never guessed.   python funnel/evaluate_overnight.py"""
import json, sys, time
from pathlib import Path
import numpy as np, pandas as pd
sys.path.insert(0, str(Path(__file__).resolve().parent)); import common
REPO = common.REPO; OUT = REPO / "out"

def gpu_h(timers_file, keys):
    try: T = json.load(open(timers_file)); return sum(T.get(k, 0) for k in keys) / 3600
    except Exception: return float("nan")

def read(p):
    p = Path(p); return pd.read_csv(p) if p.exists() else None

def arm_table(judged, arms_wanted):
    rows = []
    for arm in arms_wanted:
        g = judged[judged.arms.fillna("").str.split(";").apply(lambda l: arm in l)]
        if not len(g): rows.append(dict(arm=arm, n=0)); continue
        site_ok = (g.site_near >= 1) if "site_near" in g else pd.Series(False, index=g.index)
        flagged = (g.pisa_flags.fillna("") != "") if "pisa_flags" in g else pd.Series(False, index=g.index)
        rows.append(dict(arm=arm, n=len(g), passes=int(g.consensus_pass.sum()), pass_and_site=int((g.consensus_pass & site_ok & (g.hotspot_frac >= 0.6)).sum()),
                         site_occupied=int(site_ok.sum()), median_boltz=g.b_ipsae.median(), median_v2=g.v2_ipsae.median(), flagged_frac=float(flagged.mean()),
                         median_sc=g.pisa_sc.median() if "pisa_sc" in g else np.nan, median_arom=g.pisa_n_aromatic_iface.median() if "pisa_n_aromatic_iface" in g else np.nan))
    return pd.DataFrame(rows)

def main():
    L = [f"# Overnight results ({time.strftime('%Y-%m-%d %H:%M')})", "", "*Generated by `funnel/evaluate_overnight.py` against the criteria pre-registered in `docs/OVERNIGHT_PLAN.md`. Computational evidence only.*", ""]
    done = sorted(p.name.replace("done_", "") for p in (OUT / "overnight").glob("done_*")) if (OUT / "overnight").exists() else []
    L += ["## Queue status", "", "finished steps: " + (", ".join(done) if done else "none"), ""]
    # ---------------- FimH
    J = read(OUT / "judge/fimh/judged.csv")
    L += ["## FimH mannose pocket", ""]
    if J is None: L += ["Judge not run yet (`out/judge/fimh/judged.csv` missing).", ""]
    else:
        arms = ["funnel_nocycle", "funnel", "dock_redesign", "bias0.6"]; T = arm_table(J, arms)
        cost = {"funnel_nocycle": gpu_h(OUT / "funnel/fimh/timers.json", ["1_generate", "2_mpnn", "3_fast_screen", "5_boltz_nocycle", "5_v2_nocycle"]),
                "funnel": gpu_h(OUT / "funnel/fimh/timers.json", ["1_generate", "2_mpnn", "3_fast_screen", "4_cycling", "5_boltz_cycled", "5_v2_cycled"]),
                "dock_redesign": gpu_h(OUT / "dock/fimh/funnel/timers.json", ["3_fast_screen", "4_cycling", "5_boltz_cycled", "5_v2_cycled"]),
                "bias0.6": gpu_h(OUT / "funnel_bias0.6/fimh/timers.json", ["2_mpnn", "3_fast_screen", "5_boltz_nocycle", "5_v2_nocycle"])}
        T["gpu_h"] = T.arm.map(cost)
        ctl = {a: (json.load(open(f)) if (f := OUT / "controls" / d / "controls_summary.json").exists() else None) for a, d in (("funnel", "fimh"), ("dock_redesign", "fimh_dock"))}
        T["margin_ge_0.3_frac"] = [(ctl.get(a) or {}).get("margin_ge_0_3", np.nan) / (ctl.get(a) or {}).get("n", np.nan) if ctl.get(a) else np.nan for a in T.arm]
        L += ["```", T.round(3).to_string(index=False), "```", "", "| criterion | " + " | ".join(arms) + " |", "|---|" + "---|" * len(arms)]
        def row(name, f): return "| " + name + " | " + " | ".join(f(T[T.arm == a].iloc[0]) if (T.arm == a).any() and T[T.arm == a].iloc[0].n else "not run" for a in arms) + " |"
        c1 = lambda r: ("PASS" if r.passes >= 10 else "fail") + f" ({int(r.passes)}/20)"
        c2 = lambda r: ("PASS" if r.pass_and_site >= 5 else "fail") + f" ({int(r.pass_and_site)})"
        c3 = lambda r: "no controls" if pd.isna(r["margin_ge_0.3_frac"]) else ("PASS" if r["margin_ge_0.3_frac"] >= 0.7 else "fail") + f" ({r['margin_ge_0.3_frac']:.0%})"
        c4 = lambda r: ("PASS" if r.flagged_frac <= 0.5 else "fail") + f" ({r.flagged_frac:.0%})"
        L += [row("1. >=10 of top-20 pass both models", c1), row("2. >=5 passes occupy the mannose site AND contact >=60% of hotspots", c2),
              row("3. margin >=0.3 over decoys/shuffles for >=70% of shortlist", c3), row("4. <=50% of shortlist carries a quality flag", c4), ""]
        ok = []
        for a in arms:
            r = T[T.arm == a]
            if len(r) and r.iloc[0].n and r.iloc[0].passes >= 10 and r.iloc[0].pass_and_site >= 5 and r.iloc[0].flagged_frac <= 0.5 and (pd.isna(r.iloc[0]["margin_ge_0.3_frac"]) or r.iloc[0]["margin_ge_0.3_frac"] >= 0.7):
                ok.append((r.iloc[0].pass_and_site / max(r.iloc[0].gpu_h, 1e-9) if r.iloc[0].gpu_h == r.iloc[0].gpu_h else 0, a))
        L += ["**Best route by the pre-registered rule** (meets 1-4; most site-occupying passes per GPU-hour): " + (max(ok)[1] if ok else "none meets all four criteria (see table)"), ""]
        if not any(ctl.values()): L += ["*Controls (criterion 3) have not run; any 'PASS' above is provisional.*", ""]
    # ---------------- bias on known targets
    L += ["## Interface-aromatic bias on PD-L1 and MDM2 (paired backbones)", ""]
    for tg in ("pdl1", "mdm2"):
        B = read(OUT / f"judge_bias/{tg}/judged.csv")
        if B is None: L += [f"- {tg}: not run", ""]; continue
        T = arm_table(B, ["funnel_nocycle", "bias0.6"]); d = T.set_index("arm")
        if len(d) == 2 and d.loc["funnel_nocycle", "n"] and d.loc["bias0.6", "n"]:
            dp = d.loc["bias0.6", "passes"] - d.loc["funnel_nocycle", "passes"]; ds = d.loc["bias0.6", "median_sc"] - d.loc["funnel_nocycle", "median_sc"]; da = d.loc["bias0.6", "median_arom"] - d.loc["funnel_nocycle", "median_arom"]
            verdict = "ADOPT" if (da > 0 and ds >= 0 and dp >= -2) else "do not adopt"
            L += [f"- **{tg}**: consensus passes {int(d.loc['funnel_nocycle', 'passes'])} -> {int(d.loc['bias0.6', 'passes'])} (delta {int(dp)}), median shape complementarity {d.loc['funnel_nocycle', 'median_sc']:.3f} -> {d.loc['bias0.6', 'median_sc']:.3f}, "
                  f"median aromatic contacts {d.loc['funnel_nocycle', 'median_arom']:.1f} -> {d.loc['bias0.6', 'median_arom']:.1f}: **{verdict}** (rule: aromatic contacts up, SC not down, passes not down by more than 2)", ""]
    # ---------------- rim hotspots
    R = read(OUT / "funnel/fimh_rim/final_nocycle.csv"); F = read(OUT / "funnel/fimh/final_nocycle.csv")
    L += ["## FimH with only rim hotspots (3 instead of 5)", ""]
    if R is None or F is None: L += ["not run", ""]
    else:
        f = lambda d: f"{int(d.consensus_pass.sum())}/{len(d)} pass, median consensus {d.consensus.median():.3f}, site-occupied {int((d.site_near >= 1).sum()) if 'site_near' in d else 'n/a'}"
        L += [f"- 5 pocket hotspots: {f(F)}", f"- 3 rim hotspots:    {f(R)}", ""]
    (REPO / "docs/OVERNIGHT_RESULTS.md").write_text("\n".join(L) + "\n"); print("\n".join(L))

if __name__ == "__main__": main()
