"""A shared, rule-based ranking of submission candidates that several agents can update without overwriting each other.

 designs.csv    registry, one row per design:  design_id, sequence, lineage, generator, length, parent, note      (a design is added once; sequence may be blank until its owner supplies it)
 evidence.csv   APPEND-ONLY ledger of measurements: ts, agent, design_id, metric, value, n, note                 (a correction is a NEW row; the latest row per (design, metric) wins)
 rules.json     thresholds and the tier logic's parameters (argue a change in a note, then edit this file once)
 FINAL_RANKING.csv / .md   OUTPUT, regenerated by `rank`; never edit by hand

  python ranking.py check                       validate designs/evidence against the vocabulary and the submission contract
  python ranking.py add <design> <metric> <value> --agent NAME [--n N] [--note TEXT]     append one measurement (validated; one atomic write)
  python ranking.py add-design <id> --sequence SEQ --lineage L --generator G [--parent P] [--note T]
  python ranking.py rank [--top 20]            recompute FINAL_RANKING.csv/.md and the suggested submission ROW ORDER
Directory: $RANKING_DIR (default: this file's directory).

Objectives, in the organisers' order: (1) pH-dependent binding, (2) mouse cross-reactivity at 7.4, (3) human affinity. Novelty is a veto, not a score: a PDB hit at TM >= 0.8 over >= 70% of the chain
(query-normalised `qtm`) makes a design unsubmittable. Absence of evidence is shown as such ('na', 'unscreened'), never filled in.
"""
from __future__ import annotations
import csv, json, math, os, re, sys, time
from pathlib import Path
import pandas as pd

DIR = Path(os.environ.get("RANKING_DIR") or Path(__file__).resolve().parent)
AA = re.compile(r"^[ACDEFGHIKLMNPQRSTVWY]+$")
METRICS = {   # name -> meaning
    "boltz_h_mean": "Boltz-2 grouped ipSAE (min direction), human trimer, mean over the seeds given in column n", "boltz_h_worst": "worst seed of the above",
    "boltz_m_mean": "same, mouse trimer (n = seeds)", "boltz_m_worst": "worst seed, mouse",
    "af3_h": "AlphaFold3 grouped ipSAE (min), human, mean of diffusion samples (NOT ipTM)", "af3_m": "same, mouse",
    "novelty_hits_qtm": "PDB hits with qtmscore >= 0.80 at >= 70% query coverage", "novelty_best_qtm": "best qtmscore at >= 70% coverage",
    "novelty_hits_alntm": "same count under alntmscore (adverse convention)", "novelty_best_alntm": "best alntmscore at >= 70% coverage",
    "ph_delta": "multi-pose PROPKA k_release(variant) - k_release(parent), kcal/mol, pH 6.0 vs 7.4", "ph_se": "standard error of ph_delta", "ph_npose": "number of poses behind ph_delta",
}
DEFAULT_RULES = {
    "boltz_robust": {"mean": 0.65, "worst": 0.50, "min_n": 3}, "boltz_pass": 0.50, "af3_pass": 0.50, "af3_near": 0.45,
    "mouse_pass": {"mean": 0.50, "worst": 0.50, "min_n": 3, "af3_min": 0.45}, "novelty_thin_qtm": 0.77,
    "ph_supported": {"delta": 0.50, "min_pose": 5, "z": 2.0}, "first_n": 20, "lineage_cap_share": 0.40, "alternation_window": 2, "min_len": 60, "max_len": 250,
}

def rules() -> dict:
    p = DIR / "rules.json"; r = json.loads(p.read_text()) if p.exists() else {}
    return {**DEFAULT_RULES, **r}

def load():
    d = pd.read_csv(DIR / "designs.csv", dtype=str, keep_default_na=False)
    e = pd.read_csv(DIR / "evidence.csv", dtype={"design_id": str, "metric": str, "agent": str}) if (DIR / "evidence.csv").exists() else pd.DataFrame(columns=["ts", "agent", "design_id", "metric", "value", "n", "note"])
    return d, e

def latest(e: pd.DataFrame):
    """One row per (design, metric). Precedence: MORE seeds/samples (column n) beat fewer, then the NEWEST row wins, so a correction is a new line and a 5-seed value is never
    overridden by a later 1-seed one. Returns (values, n) as wide tables indexed by design_id."""
    if not len(e): return pd.DataFrame(), pd.DataFrame()
    e = e.assign(_n=pd.to_numeric(e.n, errors="coerce").fillna(0)).sort_values(["_n", "ts"], kind="stable").drop_duplicates(["design_id", "metric"], keep="last")
    return e.pivot(index="design_id", columns="metric", values="value").astype(float), e.pivot(index="design_id", columns="metric", values="_n").astype(float)

def check(d: pd.DataFrame, e: pd.DataFrame, r: dict) -> list[str]:
    bad = []
    if not d.design_id.is_unique: bad.append("duplicate design_id in designs.csv")
    for x in d.itertuples():
        s = x.sequence
        if s and (not AA.match(s) or "C" in s or not r["min_len"] <= len(s) <= r["max_len"]): bad.append(f"{x.design_id}: sequence violates the contract (alphabet / no cysteine / {r['min_len']}-{r['max_len']} aa)")
    s = d[d.sequence != ""]; dup = s[s.duplicated("sequence", keep=False)]
    if len(dup): bad.append("identical sequences under different ids: " + ", ".join(dup.design_id))
    unk = set(e.design_id) - set(d.design_id); bad += [f"evidence for unregistered design '{u}'" for u in sorted(unk)]
    bad += [f"unknown metric '{m}'" for m in sorted(set(e.metric) - set(METRICS))]
    return bad

def classify(v: pd.Series, nn: pd.Series, r: dict) -> dict:
    g = lambda k: (None if k not in v.index or pd.isna(v[k]) else float(v[k])); ns = lambda k: (0 if k not in nn.index or pd.isna(nn[k]) else int(nn[k]))
    hm, hw, hn = g("boltz_h_mean"), g("boltz_h_worst"), ns("boltz_h_mean"); a3h = g("af3_h"); mm, mw, mn = g("boltz_m_mean"), g("boltz_m_worst"), ns("boltz_m_mean"); a3m = g("af3_m")
    br = r["boltz_robust"]
    boltz = "na" if hm is None else ("robust" if (hm >= br["mean"] and (hw or 0) >= br["worst"] and hn >= br["min_n"]) else ("pass" if hm >= r["boltz_pass"] else "fail"))
    af3 = "na" if a3h is None else ("pass" if a3h >= r["af3_pass"] else ("near" if a3h >= r["af3_near"] else "fail"))
    mp = r["mouse_pass"]
    mouse = "na" if mm is None else ("pass" if (mm >= mp["mean"] and (mw or 0) >= mp["worst"] and mn >= mp["min_n"] and (a3m is None or a3m >= mp["af3_min"])) else "fail")
    hq, bq, ha = g("novelty_hits_qtm"), g("novelty_best_qtm"), g("novelty_hits_alntm")
    nov = "unscreened" if hq is None else ("fail" if hq > 0 else ("thin" if ((bq or 0) >= r["novelty_thin_qtm"] or (ha or 0) > 0) else "clean"))
    pd_, se, npz = g("ph_delta"), g("ph_se"), g("ph_npose"); pr = r["ph_supported"]
    ph = "none" if pd_ is None or pd_ < pr["delta"] else ("supported" if ((npz or 0) >= pr["min_pose"] and se is not None and pd_ - pr["z"] * se > 0) else ("single-pose" if (npz or 0) < pr["min_pose"] else "unconfirmed"))
    ok_b = boltz in ("robust", "pass")
    if nov == "fail": tier = "X"                                                    # structurally known: unsubmittable whatever the oracles say
    elif ok_b and af3 == "pass" and nov in ("clean", "thin"): tier = "A"              # consensus of the two models (1 Boltz seed is enough; more seeds only add robustness)
    elif ok_b and (af3 in ("near", "na") or nov == "unscreened") and not (af3 == "fail"): tier = "B"
    elif mouse == "pass" and nov == "clean" and (ok_b or af3 in ("pass", "near")): tier = "B"
    elif ok_b or mouse == "pass": tier = "C"                                        # includes: one model passes, the other rejects (disagreement)
    else: tier = "D"
    merit = (hm + a3h) / 2 if (hm is not None and a3h is not None) else ((hm or 0) * 0.85 if hm is not None else 0.0)
    return dict(tier=tier, boltz_h=boltz, af3_h=af3, mouse=mouse, novelty=nov, ph=ph, merit=round(merit, 3), robust=int(boltz == "robust"))

def row_order(ranked: pd.DataFrame, r: dict) -> list[str]:
    """Submission ORDER (the first N are screened in the order submitted). Tiers are never reordered: inside the best remaining tier pick the best design whose lineage is under its share of
    the first N and differs from the previous row; if none qualifies relax adjacency, then the cap, but never move a lower tier above a higher one."""
    cap = max(1, int(r["lineage_cap_share"] * r["first_n"])); pool = [x for x in ranked.itertuples() if x.tier != "X" and x.contract == "ok"]; out, cnt = [], {}
    while pool:
        best = min(x.tier for x in pool); tier = [x for x in pool if x.tier == best]
        win = tier[: r["alternation_window"]]       # diversity may move a design down only a little: look at the next few in merit order, not the whole tier
        pick = (next((x for x in win if cnt.get(x.lineage, 0) < cap and (not out or out[-1].lineage != x.lineage)), None) or next((x for x in tier if cnt.get(x.lineage, 0) < cap), None) or tier[0])
        out.append(pick); pool.remove(pick); cnt[pick.lineage] = cnt.get(pick.lineage, 0) + 1
    return [x.design_id for x in out]

def rank(top: int | None = None) -> pd.DataFrame:
    d, e = load(); r = rules(); bad = check(d, e, r)
    if bad: raise SystemExit("ranking inputs are invalid:\n  " + "\n  ".join(bad))
    L, N = latest(e); rows = []
    for x in d.itertuples():
        v = L.loc[x.design_id] if len(L) and x.design_id in L.index else pd.Series(dtype=float); nn = N.loc[x.design_id] if len(N) and x.design_id in N.index else pd.Series(dtype=float); c = classify(v, nn, r)
        who = ",".join(sorted(set(e[e.design_id == x.design_id].agent))) if len(e) else ""
        rows.append(dict(design_id=x.design_id, lineage=x.lineage, generator=x.generator, length=(len(x.sequence) if x.sequence else (x.length or "")), **c,
                         contract=("ok" if x.sequence else "sequence needed"), missing=",".join(k for k in ("boltz_h_mean", "af3_h", "boltz_m_mean", "novelty_hits_qtm") if k not in v.index or pd.isna(v.get(k))), evidence_by=who, sequence=x.sequence, note=x.note))
    df = pd.DataFrame(rows); po = {"supported": 0}; mo = {"pass": 0, "na": 1, "fail": 2}      # only a multi-pose, significant pH shift counts as pH evidence (one pose has a spread of ~0.9 kcal/mol)
    df["_k"] = list(zip(df.tier.map({"A": 0, "B": 1, "C": 2, "D": 3, "X": 4}), df.ph.map(lambda x: po.get(x, 1)), df.mouse.map(mo), (df.novelty == "thin").astype(int), -df.robust, -df.merit)); df = df.sort_values("_k", kind="stable").drop(columns="_k").reset_index(drop=True)
    df.insert(0, "rank", range(1, len(df) + 1)); order = row_order(df, r); df["row_order"] = df.design_id.map({k: i + 1 for i, k in enumerate(order)})
    return df

def write(df: pd.DataFrame, top: int | None = None):
    df.to_csv(DIR / "FINAL_RANKING.csv", index=False); r = rules(); n = top or r["first_n"]
    ordr = df[df.row_order.notna()].sort_values("row_order")
    L = [f"# Final ranking (regenerated {time.strftime('%Y-%m-%d %H:%M')} from `evidence.csv` by `ranking.py rank`; do not edit)", "",
         "Tiers: **A** Boltz-2 >= 0.5 AND AlphaFold3 >= 0.5 on human (the two-model consensus; extra Boltz seeds add robustness, not eligibility) with a clean/thin novelty result; **B** passes on one model with the other near/missing (or novelty unscreened), or is a novelty-clean mouse binder; "
         "**C** the models disagree (one passes, the other rejects); **D** below; **X** excluded (novelty fail). Within a tier: pH evidence, then mouse, then a CLEAN novelty margin before a thin one, then 5-seed robustness, then mean of the two oracles. `row_order` is the suggested submission order (lineage-capped, no adjacent repeats).", "",
         f"## Suggested submission order (first {n} are screened, in this order)", "", "| row | design | lineage | tier | merit | boltz h | af3 h | mouse | novelty | pH | missing |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for x in ordr.head(n).itertuples(): L.append(f"| {int(x.row_order)} | {x.design_id} | {x.lineage} | {x.tier} | {x.merit} | {x.boltz_h} | {x.af3_h} | {x.mouse} | {x.novelty} | {x.ph} | {x.missing or '-'} |")
    ex = df[df.tier == "X"]; L += ["", f"## Counts", "", df.tier.value_counts().sort_index().to_string(), "", f"## Excluded (novelty fail): {', '.join(ex.design_id) if len(ex) else 'none'}",
                                  "", f"## Not yet orderable (sequence needed): {', '.join(df[df.contract != 'ok'].design_id) or 'none'}"]
    (DIR / "FINAL_RANKING.md").write_text("\n".join(L) + "\n")

def add(design, metric, value, agent, n=None, note=""):
    d, _ = load()
    if design not in set(d.design_id): raise SystemExit(f"'{design}' is not in designs.csv: add it first (add-design)")
    if metric not in METRICS: raise SystemExit(f"unknown metric '{metric}'; allowed: {', '.join(METRICS)}")
    v = float(value)
    if math.isnan(v) or math.isinf(v): raise SystemExit("value must be a finite number")
    line = [time.strftime("%Y-%m-%dT%H:%M:%S"), agent, design, metric, repr(v), "" if n is None else n, note.replace("\n", " ")]
    p = DIR / "evidence.csv"
    if not p.exists():          # create it WITH its header atomically: write a temp file, hard-link it into place (fails harmlessly if another writer won the race)
        tmp = DIR / f".evidence.{os.getpid()}.{time.time_ns()}.tmp"; tmp.write_text("ts,agent,design_id,metric,value,n,note\n")
        try: os.link(tmp, p)
        except FileExistsError: pass
        finally: tmp.unlink(missing_ok=True)
    import io; b = io.StringIO(); csv.writer(b).writerow(line)
    with open(p, "a") as fh: fh.write(b.getvalue())      # one write call on an O_APPEND file: concurrent appenders do not interleave lines

def add_design(design, sequence, lineage, generator, parent="", note=""):
    d, _ = load()
    if design in set(d.design_id): raise SystemExit(f"'{design}' already registered")
    if sequence and (not AA.match(sequence) or "C" in sequence): raise SystemExit("sequence must be canonical amino acids, uppercase, no cysteine")
    b = __import__("io").StringIO(); csv.writer(b).writerow([design, sequence, lineage, generator, len(sequence) if sequence else "", parent, note.replace("\n", " ")])
    with open(DIR / "designs.csv", "a") as fh: fh.write(b.getvalue())

def main(a):
    import argparse
    if not a or a[0] in ("-h", "--help"): print(__doc__); return 0
    cmd, rest = a[0], a[1:]
    if cmd == "check":
        d, e = load(); bad = check(d, e, rules()); print("\n".join(bad) if bad else f"ok: {len(d)} designs, {len(e)} evidence rows"); return 1 if bad else 0
    if cmd == "rank":
        ap = argparse.ArgumentParser(); ap.add_argument("--top", type=int); x = ap.parse_args(rest); df = rank(x.top); write(df, x.top); print((DIR / "FINAL_RANKING.md").read_text()); return 0
    if cmd == "add":
        ap = argparse.ArgumentParser(); ap.add_argument("design"); ap.add_argument("metric"); ap.add_argument("value"); ap.add_argument("--agent", required=True); ap.add_argument("--n"); ap.add_argument("--note", default="")
        x = ap.parse_args(rest); add(x.design, x.metric, x.value, x.agent, x.n, x.note); print("appended"); return 0
    if cmd == "add-design":
        ap = argparse.ArgumentParser(); ap.add_argument("design"); ap.add_argument("--sequence", default=""); ap.add_argument("--lineage", required=True); ap.add_argument("--generator", required=True); ap.add_argument("--parent", default=""); ap.add_argument("--note", default="")
        x = ap.parse_args(rest); add_design(x.design, x.sequence, x.lineage, x.generator, x.parent, x.note); print("registered"); return 0
    print(__doc__); return 1

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
